# Generated by Django 4.0.3 on 2022-03-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('n_bien_nacional', models.CharField(max_length=255, unique=True, verbose_name='Numero de Bien')),
                ('procesador', models.CharField(choices=[('i3', 'I3'), ('i5', 'I5'), ('i7', 'I7')], default='i3', max_length=2, verbose_name='Procesador')),
                ('ram', models.CharField(help_text='1GB, 1024MB, 512MB, 1TB, etc', max_length=255, verbose_name='RAM')),
                ('t_video', models.BooleanField(default=False, verbose_name='Tarjeta de Video')),
                ('t_red', models.BooleanField(default=False, verbose_name='Tarjeta de Red')),
                ('detalles', models.CharField(max_length=255, verbose_name='Detalles')),
            ],
        ),
    ]
