# Generated by Django 4.0.3 on 2022-03-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='mac',
            field=models.CharField(default='mac', max_length=255, unique=True, verbose_name='Mac'),
        ),
    ]
