# Generated by Django 4.0.3 on 2022-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='detalles',
            field=models.CharField(max_length=255, null=True, verbose_name='Detalles'),
        ),
    ]
