# Generated by Django 4.0.3 on 2022-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='hdd',
            field=models.CharField(help_text='1GB, 1024MB, 512MB, 1TB, etc', max_length=255, null=True, verbose_name='Disco Duro'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ram',
            field=models.CharField(help_text='1GB, 1024MB, 512MB, 1TB, etc', max_length=255, null=True, verbose_name='RAM'),
        ),
    ]
